M48
; DRILL file KiCad 10.0.7 date 2026-10-09T11:26:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-09T11:26:15+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.7
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X39.0Y-33.0
T2
X25.0Y-25.0
X25.0Y-27.54
X25.0Y-30.08
M30
