"""Reproduce the V1 first-order electrical and thermal estimates (SI units)."""
from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "examples/buck-48v-24v-1kw/design"


def calculate():
    vout, pout, fs, inductance = 24.0, 1000.0, 100e3, 10e-6
    current = pout / vout
    # Tolerance plus a conservative 20% inductance droop scenario, not a guarantee.
    lmin = inductance * 0.8 * 0.8
    rows = []
    for vin in (36.0, 48.0, 54.0):
        duty = vout / vin
        ripple = vout * (1 - duty) / (inductance * fs)
        ripple_max = vout * (1 - duty) / (lmin * fs)
        il2 = current**2 + ripple**2 / 12
        icin = math.sqrt(current**2 * duty * (1-duty) + duty*ripple**2/12)
        rows.append(dict(vin_V=vin, duty=duty, input_ideal_A=pout/vin,
                         input_at_95pct_A=pout/vin/0.95,
                         ripple_nominal_App=ripple, ripple_scenario_App=ripple_max,
                         peak_scenario_A=current+ripple_max/2,
                         inductor_rms_A=math.sqrt(il2), input_cap_rms_A=icin,
                         output_cap_rms_scenario_A=ripple_max/math.sqrt(12)))
    nominal = rows[1]
    il2 = nominal["inductor_rms_A"]**2
    loss = {
        "mosfet_conduction_4_devices": il2 * 0.0027 * 1.7 / 2,
        # tr+tf is a design scenario, not a datasheet switching-time promise.
        "high_side_overlap_100ns_total": 0.5*48*current*100e-9*fs,
        "reverse_recovery_budget": 2*200e-9*48*fs,
        "output_capacitance_budget": 2*335e-9*48*fs/2,
        "body_diode_deadtime_200ns_each": 2*200e-9*fs*current*0.9,
        "gate_drive_upper_budget": 4*153e-9*12*fs,
        "inductor_copper_100C": il2*0.00086*(1+0.00393*75),
        "inductor_core_budget_unverified": 4.0,
        "shunt_2mohm": il2*0.002,
        "input_capacitor_ESR_proxy": nominal["input_cap_rms_A"]**2*0.036/14,
        "output_capacitor_ESR_proxy": (nominal["ripple_nominal_App"]/math.sqrt(12))**2*0.025/4,
        "copper_connections_budget": 3.0,
        "fuse_budget": (pout/48/0.95)**2*0.00156,
        "auxiliary_input_budget": 4.5,
    }
    copper_rho_hot = 1.724e-8*(1+0.00393*75)
    path_resistance = copper_rho_hot*0.100/(0.025*70e-6*2)
    via_resistance = copper_rho_hot*0.002/(math.pi*0.0005*25e-6)
    values = dict(
        output_A=current, frequency_Hz=fs, inductance_H=inductance,
        inductance_scenario_min_H=lmin, cases=rows, losses_W=loss,
        total_loss_W=sum(loss.values()), efficiency_estimate=pout/(pout+sum(loss.values())),
        efficiency_if_loss_doubles=pout/(pout+2*sum(loss.values())),
        input_capacitance_nominal_F=14*470e-6,
        input_capacitance_min_F=14*470e-6*0.8,
        input_cap_ripple_rating_A=14*1.750,
        output_capacitance_nominal_F=4*1000e-6,
        output_capacitance_min_F=4*1000e-6*0.8,
        output_cap_ripple_rating_A=4*2.555,
        input_cap_dv_capacitive_V=current*0.5*0.5/(14*470e-6*0.8*fs),
        output_ripple_capacitive_V=rows[-1]["ripple_scenario_App"]/(8*fs*4*1000e-6*0.8),
        output_ripple_ESR_proxy_V=rows[-1]["ripple_scenario_App"]*0.025/4,
        load_step_20A_100us_cap_droop_V=20*100e-6/(4*1000e-6*0.8),
        vin_adc_at54_V=54*4.99/(121+4.99),
        vout_adc_at24_V=24*4.99/(49.9+4.99),
        current_adc_at_full_load_V=current*0.002*20,
        current_trip_A=(2.5*24/25)/(0.002*20),
        output_trip_V=2.5*(49.9+4.99)/4.99,
        temperature_trip_C=(2.5*15/25-0.6)/0.010,
        bootstrap_required_F=2*153e-9/0.5,
        power_path_100mm_25mm_2x70um_resistance_ohm=path_resistance,
        power_path_loss_W=current**2*path_resistance,
        single_via_resistance_ohm=via_resistance,
        vias32_loss_W=current**2*via_resistance/32,
        ldoregulator_loss_W=(5-1.9)*0.4+(5-3.3)*0.2,
        lc_resonance_Hz=1/(2*math.pi*math.sqrt(inductance*4*1000e-6)),
    )
    assert values["input_cap_ripple_rating_A"] > max(r["input_cap_rms_A"] for r in rows)
    assert values["output_cap_ripple_rating_A"] > max(r["output_cap_rms_scenario_A"] for r in rows)
    assert rows[-1]["peak_scenario_A"] < values["current_trip_A"] < 83
    assert 0 < values["vin_adc_at54_V"] < 3 and 0 < values["vout_adc_at24_V"] < 3
    return values


def main():
    d = calculate()
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "calculations.json").write_text(json.dumps(d, indent=2)+"\n")
    lines = ["# V1 calculation record", "", "Generated by `python -m automation.scripts.calculate_buck`.",
        "", "These are analytical estimates and explicit design scenarios, not measured performance.",
        "", "## Operating points", "", "Io = Po/Vo = 41.667 A; D = Vo/Vin; fs = 100 kHz; L = 10 uH.",
        "L scenario minimum = 10 uH x 0.8 tolerance x 0.8 droop = 6.4 uH.",
        "", "| Vin / V | Duty | Ideal Iin / A | Iin at 95% / A | Ripple nominal / App | Ripple scenario / App | Peak scenario / A | Cin RMS / A |",
        "|---|---|---|---|---|---|---|---|"]
    for row in d["cases"]:
        lines.append("| "+" | ".join(f"{row[k]:.3f}" for k in ("vin_V","duty","input_ideal_A","input_at_95pct_A","ripple_nominal_App","ripple_scenario_App","peak_scenario_A","input_cap_rms_A"))+" |")
    lines += ["", "Ripple: dIL = Vo(1-D)/(L fs); ILrms² = Io² + dIL²/12.",
        "Cin RMS² = Io² D(1-D) + D dIL²/12; Cout RMS = dIL/sqrt(12).",
        "", "## Capacitors", "",
        f"14 x 470 uF / 100 V EKY-101ELL471MM25S: {d['input_capacitance_nominal_F']*1e6:.0f} uF nominal; 5264 uF at -20%; total rating 24.50 Arms at 105 C / 100 kHz. Maximum calculated RMS is 20.98 A, so sharing must remain within approximately 16% of equal sharing. Matched parts, symmetric buses and measured can temperatures are required.",
        f"Input capacitive ripple is {d['input_cap_dv_capacitive_V']:.3f} Vpp near D=0.5; ESR/ESL adds to this. Eight 2.2 uF / 100 V X7R parts provide local commutation bypass; no nominal ceramic capacitance is credited in the bulk calculation because bias derating has not been characterized.",
        f"4 x 1000 uF / 50 V EKY-500ELL102ML25S: 4000 uF nominal, 3200 uF at -20%, 10.22 Arms rated. Worst scenario ripple: capacitive {d['output_ripple_capacitive_V']:.3f} Vpp plus impedance-based proxy {d['output_ripple_ESR_proxy_V']:.3f} Vpp. A 20 A load step for 100 us gives {d['load_step_20A_100us_cap_droop_V']:.3f} V capacitive droop plus ESR response.",
        "The manufacturers specify impedance at 100 kHz, not pure ESR. The loss and voltage terms using that impedance are approximations and cannot establish broadband behavior.",
        "", "## MOSFET and driver", "",
        "Two CSD19536KCS in parallel per leg, 100 V rated. At 54 V the static voltage margin is 46 V; ringing must be measured and kept below an 80 V engineering target. Individual 4.7 ohm gate resistors and 10 kohm gate-source pulldowns prevent uncontrolled sharing and floating gates.",
        "UCC27211DDAR runs at 12 V. Upper gate-charge budget is 2 x 153 nC per output. Charge/0.5 V requires 0.612 uF effective bootstrap capacitance. Fit 2.2 uF / 25 V plus 100 nF and require at least 1 uF effective. Driver logic inputs are driven at 3.3 V. Initial dead time is 200 ns at each edge; verify both Vgs waveforms before reducing it.",
        "Gate-drive power upper budget is 4 Qg Vg fs. 100 ns total high-side overlap is assumed; gate resistance, parasitics and Miller charge require double-pulse validation. Bootstrap operation requires a low-side refresh interval and does not permit 100% duty.",
        "", "## Nominal losses", "", "| Item | W |", "|---|---|"]
    lines += [f"| {key.replace('_',' ')} | {value:.3f} |" for key,value in d["losses_W"].items()]
    lines += [f"| Total | {d['total_loss_W']:.3f} |", "",
        f"Estimated efficiency {100*d['efficiency_estimate']:.2f}%; if total loss doubles, {100*d['efficiency_if_loss_doubles']:.2f}%. This is a scenario range, not an efficiency specification.",
        "Reverse-recovery charge of 200 nC per low-side FET and 4 W inductor core loss are explicit budgeting assumptions. They are not guaranteed part parameters. CSD19536KCS Qrr is characterized at a different current; measured losses can exceed the estimate. Coss/Qoss and recovery budget may overlap; conservative accounting is intentional.",
        "", "## Sensing and thresholds", "",
        f"Vin: 121 kohm / 4.99 kohm divider => {d['vin_adc_at54_V']:.3f} V at 54 V. Vout: 49.9 kohm / 4.99 kohm => {d['vout_adc_at24_V']:.3f} V at 24 V. Buffer voltage channels before the ADC sampling capacitors.",
        f"2 mohm four-terminal shunt and INA240A1 gain 20 => {d['current_adc_at_full_load_V']:.3f} V at full load. Hardware OCP nominal {d['current_trip_A']:.1f} A; OVP {d['output_trip_V']:.1f} V; LM61 overtemperature {d['temperature_trip_C']:.1f} C. Comparator and reference tolerances, amplifier offset, shunt heating and dynamic delay must be included in test limits.",
        "At 54 V into a short with 6.4 uH, di/dt is 8.44 A/us. The sensing/comparator chain is not certified short-circuit protection: even 3 us adds 25.3 A. The input fuse limits sustained faults, and a current-limited source is an explicit boundary condition. A fuse does not protect the MOSFET from all fast faults.",
        "", "## Copper and thermal arithmetic", "",
        f"A 100 mm x 25 mm path using two parallel 70 um copper layers at 100 C is {d['power_path_100mm_25mm_2x70um_resistance_ohm']*1e3:.3f} mohm, dissipating {d['power_path_loss_W']:.3f} W at 41.67 A. This is resistance only, not an IPC temperature-rise qualification.",
        f"A 2 mm long 0.5 mm finished-hole via with assumed 25 um barrel plating is {d['single_via_resistance_ohm']*1e3:.3f} mohm at 100 C. 32 in parallel dissipate {d['vias32_loss_W']:.3f} W at full load under equal-sharing assumption. Specify plating to the fabricator and avoid using a small signal-via group for the power path.",
        f"DSP rail budgeting: 1.9 V x 0.4 A and 3.3 V x 0.2 A. Dual LDO dissipation {d['ldoregulator_loss_W']:.2f} W from 5 V. Auxiliary 12 V rail budget <0.5 A, below the LM5164 1 A rating; a separate fan supply is required.",
        f"LC natural frequency is approximately {d['lc_resonance_Hz']:.1f} Hz. The digital compensator and transient response remain unvalidated; a firmware interface contract is supplied separately.", ""]
    (OUT / "calculations.md").write_text("\n".join(lines), encoding="utf8")
    print(json.dumps({k:d[k] for k in ('output_A','total_loss_W','efficiency_estimate','current_trip_A')},indent=2))


if __name__ == "__main__":
    main()
