"""Inspect the host using only the standard library; never install tools."""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from automation.setup.detect_kicad import ROOT, find_kicad_cli, read_config


def probe(command: list[str]) -> dict:
    try:
        result = subprocess.run(command, capture_output=True, text=True,
                                encoding="utf-8", errors="replace", timeout=15)
        return {"returncode": result.returncode,
                "output": (result.stdout + result.stderr).strip()[:1500]}
    except (OSError, subprocess.TimeoutExpired) as exc:
        return {"returncode": None, "error": str(exc)}


def mcp_names() -> dict:
    """Read server names only. Do not copy configuration, URLs or secrets."""
    result = {}
    codex = Path(os.environ.get("CODEX_HOME", str(Path.home() / ".codex")))
    config = codex / "config.toml"
    if config.is_file():
        text = config.read_text(encoding="utf-8-sig")
        names = re.findall(r'^\[mcp_servers\.([\w-]+)\]\s*$', text, re.MULTILINE)
        result["codex_declared_server_names"] = sorted(set(names))
    cursor = Path.home() / ".cursor/mcp.json"
    if cursor.is_file():
        try:
            data = json.loads(cursor.read_text(encoding="utf-8-sig"))
            result["cursor_declared_server_names"] = sorted(data.get("mcpServers", {}))
        except (ValueError, TypeError):
            result["cursor_inspection"] = "Invalid JSON; contents not recorded"
    result["scope"] = "Local declarations only; does not establish live server availability"
    return result


def plugin_locations() -> list[dict]:
    roots = [Path.home() / "Documents/KiCad", Path.home() / ".local/share/kicad"]
    if os.environ.get("APPDATA"):
        roots.append(Path(os.environ["APPDATA"]) / "kicad")
    found = []
    for root in roots:
        if not root.is_dir():
            continue
        for pattern in ("*/plugins", "*/scripting/plugins", "*/3rdparty/plugins"):
            for folder in root.glob(pattern):
                if folder.is_dir():
                    found.append({"path": str(folder),
                                  "names": sorted(p.name for p in folder.iterdir())})
    return found


def inspect() -> dict:
    cli = find_kicad_cli()
    commands = {}
    for name in ("git", "gh", "winget", "choco", "scoop"):
        path = shutil.which(name)
        commands[name] = {"path": path, "probe": probe([path, "--version"]) if path else None}
    try:
        with tempfile.TemporaryFile(dir=ROOT):
            writable = True
    except OSError:
        writable = False
    config = read_config()
    kicad_python = config.get("kicad_python")
    if not kicad_python and cli and platform.system() == "Windows":
        sibling = cli.parent / "python.exe"
        if sibling.is_file():
            kicad_python = str(sibling)
    python_probe = None
    if kicad_python:
        python_probe = probe([kicad_python, "-c",
                              "import sys, pcbnew; print(sys.version); print(pcbnew.GetBuildVersion())"])
    return {
        "schema_version": 1,
        "observed_at_utc": datetime.now(timezone.utc).isoformat(),
        "system": platform.system(), "os_version": platform.version(),
        "architecture": platform.machine(), "processor": platform.processor(),
        "python": {"path": sys.executable, "version": platform.python_version(),
                   "pcbnew_discoverable": importlib.util.find_spec("pcbnew") is not None},
        "tools": commands,
        "kicad": {"cli": str(cli) if cli else None,
                  "version_probe": probe([str(cli), "version"]) if cli else None,
                  "python": kicad_python, "python_probe": python_probe,
                  "ipc_status": "unverified; no running API connection tested",
                  "plugins_at_known_user_locations": plugin_locations()},
        "mcp": mcp_names(), "workspace_writable": writable,
        "path_entry_count": len(os.environ.get("PATH", "").split(os.pathsep)),
        "software_installation_performed": False,
    }


def render_markdown(data: dict) -> str:
    lines = ["# Host environment", "", f"Observed (UTC): {data['observed_at_utc']}", "",
             "This report is generated by `automation.setup.detect_environment`.",
             "It inspects the host and does not install software.", "",
             "| Item | Observation |", "| --- | --- |",
             f"| Operating system | {data['system']} {data['os_version']} |",
             f"| Architecture | {data['architecture']} |",
             f"| CPU | {data['processor']} |",
             f"| Python | {data['python']['version']} |",
             f"| Workspace writable | {data['workspace_writable']} |",
             f"| PATH entries inspected | {data['path_entry_count']} |"]
    for name, item in data["tools"].items():
        output = item["probe"] or {}
        detail = output.get("output", output.get("error", "not found"))
        lines.append(f"| {name} | {detail.replace(chr(10), ' ').replace('|', '/')} |")
    kicad = data["kicad"]
    lines.extend([
        f"| KiCad CLI | {kicad['cli'] or 'not found in inspected locations'} |",
        f"| KiCad Python | {kicad['python'] or 'not found'} |",
        f"| KiCad IPC | {kicad['ipc_status']} |",
        "", "## Inspection boundaries", "",
        "Local executable paths are retained in ignored `.aipe/environment.json`.",
        "A custom KiCad location must be supplied in `.aipe/local-tools.json` or",
        "`AIPE_KICAD_CLI`; discovery is not a scan of every disk.", "",
        "KiCad plugin directories observed: " + str(len(kicad["plugins_at_known_user_locations"])) + ".",
        "MCP inspection records only explicitly declared names, not credentials or",
        "remote plugin-managed servers. The project does not require a KiCad MCP.",
        "", "```json", json.dumps(data["mcp"], indent=2), "```", "",
        "Actual KiCad file parsing, ERC, DRC, exports and IPC remain unverified until",
        "the integration smoke test has run. Software installation is subject to the",
        "user's separate confirmation of software and directory.", "",
    ])
    if kicad["version_probe"]:
        lines.extend(["## KiCad version probe", "", "```json",
                      json.dumps(kicad["version_probe"], indent=2), "```", ""])
    if kicad["python_probe"]:
        lines.extend(["## KiCad Python probe", "", "```json",
                      json.dumps(kicad["python_probe"], indent=2), "```", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--markdown", type=Path)
    args = parser.parse_args()
    data = inspect()
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
        print(f"Environment report: {args.output}")
    else:
        print(text)
    if args.markdown:
        args.markdown.parent.mkdir(parents=True, exist_ok=True)
        args.markdown.write_text(render_markdown(data), encoding="utf-8")
        print(f"Markdown report: {args.markdown}")


if __name__ == "__main__":
    main()
